# Gradle and mod metadata
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.daemon=true

# Project coordinates
modGroup=com.mrwizard94
archivesBaseName=biglittlefixes
modName=Big Little Fixes
modId=biglittlefixes
modVersion=1.0.0
minecraftVersion=1.20.1
javaVersion=17

# Publishing/group
mavenGroup=com.mrwizard94
